# note: we do not run prod service with docker-compose, we use it just for
# configuring the production build
services:
  prod:
    image: release-hatch-prod
    build:
      context: ..
      # path relative to context
      dockerfile: docker/Dockerfile
      # the prod stage in the Dockerfile
      target: release-hatch-prod
      # should speed up the build in CI, where we have a cold cache
      cache_from:  # should speed up the build in CI, where we have a cold cache
        - ghcr.io/opensafely/base-docker
        - ghcr.io/opensafely/release-hatch
      args:
        # this makes the image work for later cache_from: usage
        - BUILDKIT_INLINE_CACHE=1
        # env vars supplied by just
        - BUILD_DATE
        - GITREF
    # use dockers builitin PID daemon
    init: true
    # release-hatch's default port is 8001
    ports:
      - "8001:8001"
    # relative to docker-compose.yaml
    volumes:
      - ../workspaces:/workspaces
    # ensure WORKSPACES environent points volume
    environment:
      WORKSPACES: /workspaces

  # main development service
  dev:
    extends:
        service: prod
    image: release-hatch-dev
    container_name: release-hatch-dev
    # running as a specific user id allows files written to mounted volumes by
    # the docker container's default user to match the host uid, for convienience.
    user: ${DOCKER_USERID:-1000}
    build:
      # the dev stage in the Dockerfile
      target: release-hatch-dev
      # pass the user id as build arg (default to 1000)
      args:
        - USERID=${DOCKER_USERID:-1000}
    # paths relative to docker-compose.yaml file
    env_file:
      - ../.env
    volumes:
      - ..:/app

  # test runner service - uses dev-image with a different commnd
  test:
    extends:
        service: dev
    container_name: release-hatch-test
    # override command
    command: /opt/venv/bin/pytest
    # different default test env
    env_file:
      - ../.test.env
