---
name: CI

env:
    IMAGE_NAME: release-hatch
    REGISTRY: ghcr.io

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: extractions/setup-just@v1
      - name: Check formatting, linting and import sorting
        run: just check

  test:
    needs: [check]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: extractions/setup-just@v1
      - name: Run tests
        run: |
          just test

  docker:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: extractions/setup-just@v1
      - name: Build docker image and run tests in it
        run: |
          # build docker and run test
          just docker-test
          # test that prod image builds
          just docker-build prod
      - name: Login to Packages Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish docker image
        if: github.ref == 'refs/heads/main'
        run: |
            # use new GITHUB_TOKEN auth
            IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
            docker tag $IMAGE_NAME $IMAGE_ID:latest
            docker push $IMAGE_ID:latest


  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          failure-threshold: error
