---
name: CI

env:
    IMAGE_NAME: release-hatch
    REGISTRY: ghcr.io

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb  # v1.4.0
      - name: Check formatting, linting and import sorting
        run: just check

  test:
    needs: [check]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb  # v1.4.0
      - name: Run tests
        run: |
          just test

  docker:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - uses: extractions/setup-just@aa5d15c144db4585980a44ebfdd2cf337c4f14cb  # v1.4.0
      - name: Build docker image and run tests in it
        run: |
          # build docker and run test
          just docker-test
          # docker-test will build the dev image by default, so build the prod image
          just docker-build prod
          # TODO smoketests
      - name: Login to Packages Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9  # v1.10.0
        if: github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish docker image
        if: github.ref == 'refs/heads/main'
        run: |
            IMAGE_ID=$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME
            docker tag $IMAGE_NAME-prod $IMAGE_ID:latest
            docker push $IMAGE_ID:latest


  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          failure-threshold: error
          dockerfile: docker/Dockerfile
